### ISSUE TITLE
Remove access-control origin (CORS) limitation

### ISSUE THREAD

**Issue by qtrandev** [adam-s/trolley-tracker#8] opened 2016-03-10 00:01 UTC
I'm getting this error testing out a map client. Can you check why?

XMLHttpRequest cannot load http://trolley-tracker.herokuapp.com/api/trolleys. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

**Comment by qtrandev** [comment] 2016-03-10 00:13
Check if solution is here: http://stackoverflow.com/questions/11001817/allow-cors-rest-request-to-a-express-node-js-application-on-heroku

**Comment by adam-s** [comment] 2016-03-10 00:18
This is on your code not the trolley-tracker. I'm the third party resource. What is happening is your server is telling the browser not to allow access to any third party resources. It specifies the domains that the app / webpage are allowed to access resources from. On your server, it needs to set `Access-Control-Allow-Origin:` in the response HEADER to allow access at trolley-tracker.herokuapp.com. We will figure this one out.

**Comment by qtrandev** [comment] 2016-03-10 00:24
Isn't this server yours and running on your Heroku account? I'm the client.

**Comment by qtrandev** [comment] 2016-03-10 00:27
Localhost is what I use to test locally. Same problem when running on GitHub:

"XMLHttpRequest cannot load http://trolley-tracker.herokuapp.com/api/trolleys. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://qtrandev.github.io' is therefore not allowed access."

**Comment by adam-s** [comment] 2016-03-10 00:29
I think you are serving a static page. If it is on a apache server the cross origin resource sharing (CORS) can be enabled by altering the .htaccess file. [Here is documentation on how to do that.](http://enable-cors.org/server_apache.html). [Here is another example.](http://blog.revolunet.com/blog/2013/10/03/universal-CORS-htaccess/)

If you go to http://trolley-tracker.herokuapp.com/api/trolleys, you get a geoJSON object. However, if you have an app whose origin is localhost or http://example.com and it makes a `XMLHttpRequest` (AJAX) to another server which is not localhost or http://example.com, the CORS policy will throw an error. This is for security reasons.

**Comment by qtrandev** [comment] 2016-03-10 00:30
Email me your phone number to qtrandev at gmail.com . Let's talk about this.

**Comment by adam-s** [comment] 2016-03-10 00:57
Unfortunately, there is no support for [cross - origin resource sharing (CORS) on GitHub pages](http://stackoverflow.com/questions/26416727/cross-origin-resource-sharing-on-github-pages).

**Comment by adam-s** [comment] 2016-03-10 17:10
Works by design. Closing issue.

**Closed by adam-s** 2016-03-10 17:10 UTC
